Multiple code changes Updating travis file to bubble up failures. Adding/updating feature tests Adding test tags for travis Code cleanup

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -67,13 +67,18 @@ script:
   - export P1="_p1"
   - export P2="_p2"
   - export P3="_p3"
+  - export STATUS=0
+  - export CURRENT_STATUS=0 
   # Run Cucumber @tag specific tests
   - ls -alt results
   - rm results/*
+  # Get status of run into CURRENT_STATUS. Update STATUS only if it is 0. So failures should be preserved across runs till the end
   - |
     if [ "$CUC_TAG" == "@treatment_arm" -o "$CUC_TAG" == "@ion_reporter" -o "$CUC_TAG" == "@patients" ]; then
       cd uMATCH/PedMATCH
       bundle exec parallel_cucumber features/ -o '-r features/step_definitions/ -r features/support/ -t $CUC_TAG$P1,$CUC_TAG$P2 --format json --out ../../results/output-$CUC_TAG$P1-$TEST_ENV_NUMBER.json --expand' -n 2
+      CURRENT_STATUS=$?
+      if [ "$STATUS" == 0 ]; then STATUS=$CURRENT_STATUS; fi
       cd ../..
     fi
   
@@ -81,6 +86,8 @@ script:
     if [ "$CUC_TAG" == "@admin_api" ]; then
       cd nci-admin-api-bddtests
       cucumber --tags $CUC_TAG$P1,$CUC_TAG$P2 --format json --out ../results/output-$CUC_TAG$P1-$TEST_ENV_NUMBER.json --expand
+      CURRENT_STATUS=$?
+      if [ "$STATUS" == 0 ]; then STATUS=$CURRENT_STATUS; fi
       cd ..
     fi
 #  - aws s3 cp results/ s3://bdd-test-data/report_test --region us-east-1 --recursive
@@ -96,11 +103,15 @@ script:
     if [ "$CUC_TAG" == "@admin_ui" ]; then
       cd nci-admin-ui-bddtests/;
       protractor conf.js --cucumberOpts.tags='~@broken' --cucumberOpts.tags='$CUC_TAG$P1,$CUC_TAG$P2' --troubleshoot
+      CURRENT_STATUS=$?
+      if [ "$STATUS" == 0 ]; then STATUS=$CURRENT_STATUS; fi
       cd ..
     else
       if [ "$CUC_TAG" == "@ui" -o "$CUC_TAG" == "@demo" ]; then
         cd nci-match-ui-bddtests/
         protractor config.js --cucumberOpts.tags='~@broken' --cucumberOpts.tags=$CUC_TAG$P1,$CUC_TAG$P2 --troubleshoot
+        CURRENT_STATUS=$?
+        if [ "$STATUS" == 0 ]; then STATUS=$CURRENT_STATUS; fi
         cd ..
       fi
     fi
@@ -113,6 +124,7 @@ script:
   - cd ..
   - ls -alt
   - mv results/ results_critical/; mkdir results
+  - TRAVIS_TEST_RESULT=$STATUS
 after_success:
   #Run P3 cucumber tests
   - cd uMATCH/PedMATCH; bundle exec parallel_cucumber features/ -o '-r features/step_definitions/ -r features/support/ -t $CUC_TAG$P3 --format json --out ../../results/output-$CUC_TAG$P3-$TEST_ENV_NUMBER.json --expand' -n 2
